### ISSUE TITLE
[bugs] Enabling the massCraftUseRecipeBook would make msscraft get stuck when the inventory is full of emerald blocks.

### ISSUE THREAD

**Issue by AsOne2020** [sakura-ryoko/itemscroller#17]
Enabling massCraftUseRecipeBook option will cause crafting to get stuck when the backpack is full of emerald blocks
![QQ20240828-233549](https://github.com/user-attachments/assets/5f894972-1ad5-4e36-97cf-9c85eebb93b9)

**Comment by sakura-ryoko** [comment]
Confirmed bug.  And to be clear, it doesn't need to be Emerald Blocks; just anything that fills the Inventory instead of throwing the items on the ground.

**Comment by sakura-ryoko** [comment]
Fixed bug under Snapshot; will work to back port this and many other fixes for 1.21.

**Comment by sakura-ryoko** [comment]
See https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21-0.24.1-sakura.1

**Comment by AsOne2020** [comment]
> See https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21-0.24.1-sakura.1

The BUG was not fixed properly and the same problem still occurs

**Comment by AsOne2020** [comment]
Even if the inventory has enough empty space stack, it can get stuck, and the larger the massCraftIterations, the more likely it is to get stuck

**Comment by sakura-ryoko** [comment]
It worked fine for me in testing, and on a server as is.  Perhaps the server has lag or another problem blocking it from working?
Does the "Normal" mass crafting work?

**Comment by AsOne2020** [comment]
> It worked fine for me in testing, and on a server as is.  Perhaps the server has lag or another problem blocking it from working?
> Does the "Normal" mass crafting work?

the normal mass crafting （massCraftUseRecipeBook:false）works correctly
