### ISSUE TITLE
In version 1.21.3, When I use "MassCraft", the recipe got an error

### ISSUE THREAD

**Issue by HeWu235** [sakura-ryoko/itemscroller#41]
This was the case when I tested it in a single-player world

![Image](https://github.com/user-attachments/assets/96416466-219c-4f4c-a0a0-f6a8ae3e9199)

The recipe I saved was four threads to make white wool, but what it detected was using colored wool dyeing to get white wool
The version I'm using is "itemscroller-fabric-1.21.3-0.25.4-sakura.1"
This is my configuration interface

![Image](https://github.com/user-attachments/assets/448552fe-c9cc-40a3-8d90-7ca80236fdf9)

Here's my mod

![Image](https://github.com/user-attachments/assets/e8daab7e-38a7-496e-83ef-a1134aa6dee3)

![Image](https://github.com/user-attachments/assets/4221d633-c496-44bf-8b23-3459cb4fe971)

**Comment by sakura-ryoko** [comment]
Try deleting your itemscroller recipe's file completely (out of the itemscroller folder) and trying again.

**Comment by HeWu235** [comment]
I tried your method, but it didn't work,Crafting white wool is still tied to dyeing it, not thread

**Comment by sakura-ryoko** [comment]
Post your `recipes_(world).nbt` file here that is doing this.  It should be in the `(Instance)/itemscroller` folder.  Also; are you using `massCraftUsesRecipeBook` mode ?

**Comment by HeWu235** [comment]
Strangely, he would sometimes use thread to synthesize white wool, and dyeing it would have no effect

![Image](https://github.com/user-attachments/assets/30c42b4b-5595-470c-8f71-91b9bc55029a)

[recipes_____.zip](https://github.com/user-attachments/files/18723495/recipes_____.zip)

**Comment by HeWu235** [comment]
Strangely, he would sometimes use thread to synthesize white wool, and dyeing it would have no effect

![Image](https://github.com/user-attachments/assets/b281fdf6-0b7d-432e-85d5-8a8cf903a935)

[recipes_____.zip](https://github.com/user-attachments/files/18723502/recipes_____.zip)

I have massCraftUsesRecipeBook enabled and it works fine when I close him

**Comment by sakura-ryoko** [comment]
Can you please post it without using a ZIP file

**Comment by HeWu235** [comment]
![Image](https://github.com/user-attachments/assets/76df97b4-b2d8-4d33-9632-dbbf55c6b73e)

It is not possible to publish files with the NBT suffix directly

**Comment by sakura-ryoko** [comment]
I have tried this from 25e06a through 1.21.3, and have not been able to reproduce this problem.

![Image](https://github.com/user-attachments/assets/03ad6ceb-6b88-47ba-b6a7-06354576b93d)
![Image](https://github.com/user-attachments/assets/405df5ef-00b8-4d9c-9b67-74d8a84772e9)
![Image](https://github.com/user-attachments/assets/151566a9-4bca-4d58-8a06-a684d6ddd3fe)

There was a bug that was similar to what your experiencing in older versions closer to the 1.21.2 snapshot cycle where similar problems were happening; but that bug has long since been fixed.

This is what my debugging code looks like when it makes a positive Recipe Book match.

```
[10:44:51] [Render thread/INFO] (malilib) loadAllConfigs()
compare() --> size left [9], right [4]
DUMP [LF] -->
LF[0] // [64 minecraft:string]
LF[1] // [64 minecraft:string]
LF[2] // [0 minecraft:air]
LF[3] // [64 minecraft:string]
LF[4] // [64 minecraft:string]
LF[5] // [0 minecraft:air]
LF[6] // [0 minecraft:air]
LF[7] // [0 minecraft:air]
LF[8] // [0 minecraft:air]
DUMP END [LF]
DUMP [RT] -->
RT[0] // [minecraft:string]// []
RT[1] // [minecraft:string]// []
RT[2] // [minecraft:string]// []
RT[3] // [minecraft:string]// []
DUMP END [RT]
 compare() [0] left [64 minecraft:string] / [0] right [minecraft:string]
 not valid (Test test) compare() [1] left [64 minecraft:string] / [1] right [minecraft:string]
 not valid (Test test) compare() [3] left [64 minecraft:string] (Advance Left), right [2]
 compare() [3] left [64 minecraft:string] / [2] right [minecraft:string]
 not valid (Test test) compare() [4] left [64 minecraft:string] / [3] right [minecraft:string]
 not valid (Test test) PASS
[10:44:51] [Render thread/INFO] (itemscroller) onAddToRecipeBook(): Positive Match for result stack: [1 minecraft:white_wool] networkId [1301]
```

Where you can see the correct RecipeNetworkId being found.

**Comment by sakura-ryoko** [comment]
Of course using your recipes_.nbt the problem only occurs; but as soon as I replace the recipe it works as expected.  ItemScroller is supposed to VERIFY your NetworkRecipeId based on the saved recipe as soon as you login.  If it fails to match the recipe; then it keeps the invalid recipe saved.

The debugging steps are shown above when it scans your ClientRecipeBook for a crafting result match; and then it compares the 3x3 crafting grid to what comes from Minecraft.  The `LF` is the saved recipe; and the `RT` is the data in your ClientRecipeBook.

**Comment by sakura-ryoko** [comment]
Speaking of which; I found an issue with the Dye part.  The problem occurs when you put the the Dye _AFTER_ the wool instead of before the wool.  While I work on this; save your Dye Recipe with the Dye First before the Wool.

**Comment by HeWu235** [comment]
I'm having this problem not just in version 1.21.3; I updated my own client to version 1.21.4 and this problem still occurs. It's probabilistic, sometimes good, sometimes bad. Not only is this recipe limited, but there is also a chance that this will be encountered in other items with multiple crafting recipes, and I'll look into this issue later to see how this bug is triggered. I'll message you again at that time.

**Comment by sakura-ryoko** [comment]
I know why the bug is triggered because the recipe book in the game does not list the wool recipe with the dye after; it lists it first; where the Shulker Box Dye recipe has the Dye listed _AFTER_ the shulker.  They are shapeless recipe's but in the logic of the Mod; it needs them to be in order.  I am working to make a fix.

**Comment by sakura-ryoko** [comment]
Problem that I found has been fixed by:
https://github.com/sakura-ryoko/itemscroller/releases/tag/1.21.3-0.25.4-sakura.3

Please try the new build, based on malilib sakura.5

**Comment by HeWu235** [comment]
Thanks for taking some time to look into this bug, but I used the latest itemscroller and maililb, but the problem persists, I tried both the 1.21.3 version and the 1.21.4 version, both have this problem, and I only added these two mods.I will make a video and send it to you.

https://github.com/user-attachments/assets/3fb5ea3e-ff9d-454f-8afb-68c3a8c7fdd3

I've also tried deleting the itemsroller folder and config folder, but he still gets this issue. Using thread to craft white wool or dyeing to get white wool will always have some problems between the two

**Comment by sakura-ryoko** [comment]
Does it continue to do that even after closing the screen and re-opening it?  There is some funny business with the game that forces you to do this after doing certain mass crafting operations.  I have not seen this in my testing as you have shown.

Save Recipe.  Close Crafting Screen; then try to craft and see if it still does it.  I believe the reason for this is how Minecraft tries to "scramble" / "obfuscate" your crafting input away from the real values / items when crafting by normal means.

In previous versions; they added this system called "Ghost Recipe" which is basically a Dummy Recipe that only references the REAL recipe.  I don't know if it was meant as some kind of anti-cheat mechanism.  The way for Item Scroller to disregard this system is usually by just closing / reopening the crafting screen.

I am only asking to see if this is the case.

**Comment by HeWu235** [comment]
After the above issue, I went back to the title screen, and when I re-entered the game, he seemed to be normal
So every time I have this kind of problem, I need to quit the game and re-enter to solve it

**Comment by HeWu235** [comment]
So is this problem solved? I'd love to see you fix this so I don't have to restart the game if I run into this kind of problem in the future

**Comment by sakura-ryoko** [comment]
> So is this problem solved? I'd love to see you fix this so I don't have to restart the game if I run into this kind of problem in the future

You shouldn't need to restart the game.  You should only need to close the crafting window and reopen it by simply pressing Esc and then clicking on the crafting table again.

**Comment by HeWu235** [comment]
Are you sure? I tried your method, and even though I closed crafting window and opened it again, he was still wrong

https://github.com/user-attachments/assets/6f47e1d9-3ed5-44c4-b90a-bee1c32d8cdf

I've found that when I save a recipe and don't craft it, exit the crafting interface, and then click on the workbench, it works fine. If I save the recipe and go straight to crafting, he will have some problems, and closing the crafting interface and reopening the workbench has no effect

**Comment by sakura-ryoko** [comment]
Yes, as I've stated; it's a Vanilla function that "bait and switches" the crafting results; so without closing the screen after saving; it will break the data being saved with the "Ghost Recipe" instead of the real recipe; which in most cases has it's own Recipe Network Id that probably points to a different recipe; so the process like I've said is what fixes it & has it reliably work after that initial process.

**Comment by HeWu235** [comment]
From what you say, it doesn't seem like it's a bug, it's a feature of the mod itself, thank you for answering my questions, this issue can be closed

**Comment by sakura-ryoko** [comment]
> From what you say, it doesn't seem like it's a bug, it's a feature of the mod itself, thank you for answering my questions, this issue can be closed

I can still look into this when I get a chance to try to bypass this "Ghost Recipe" part that messes these steps up; but generally the initial problem of the Shapeless Recipe not saving correctly at all has been fixed also.

**Comment by HeWu235** [comment]
Looking forward to your good news
